site_name: Guy's Docs
site_description: Simple GUI (using chrome) for python

theme:
    name: 'material'
    palette:
        primary: 'purple'
        accent: 'purple'

repo_name: manatlan/guy
repo_url: https://github.com/manatlan/guy
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Example: 'simplest.md'
    - Install: 'install.md'
    - Anatomy: anatomy.md
    - Server side: server.md
    - Client side: client.md
    - Multiple Instance: multiple.md
    - Run guy's app: run.md
    - Demo: demo.md
    - How-to:
        - From wuy to guy: howto_migrate_from_wuy_to_guy.md
        - Freeze exe/windows: howto_build_exe_windows.md
        - Release an APK/android: howto_build_apk_android.md
        - Release a pypi/whl/package: howto_build_whl_package.md
markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition      